version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:0.5.23
    container_name: adeo_chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

networks:
  default:
    name: adeo_network
    external: true