version: '3.8'
services:
  evaluation:
    build: 
      context: ../../
      dockerfile: services/evaluation/Dockerfile
    container_name: adeo_evaluation
    ports:
      - "8003:8000"
    volumes:
      - ../../services/evaluation:/app/services/evaluation
    env_file:
      - ../../.env
    environment:
      - API_GATEWAY_URL=http://adeo_api_gateway:8000

networks:
  default:
    name: adeo_network
    external: true